version: '3'

services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./tmp/db:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_HOST_AUTH_METHOD: trust
  app:
    build: .
    command: node server.js
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    # depends_on:
    #   - db